# This is a basic workflow to help you get started with Actions

name: HEARTBEAT

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Heartbeat
        run: |
          [[ `curl -s https://ohmyrss.com/api/heartbeat` =~ OK ]]
